INSERT INTO public."Usuario"(
	"Id", "Nome", "Login", "Password", "Funcao")
	VALUES 
(gen_random_uuid (), 'Maria Costa','mariacosta', 'mariacosta', 'Empregado'),
(gen_random_uuid (), 'Aparececida Kaoo','apareceriakoo', 'apareceriakoo', 'Empregado'),
(gen_random_uuid (), 'Ana Maria Lopes','anamaria', 'anamaria', 'Gerente'),
(gen_random_uuid (), 'Beatriz Rosa','beatrizrosa', 'beatrizrosa', 'Empregado'),
(gen_random_uuid (), 'Claudia Matos','claudiamatos', 'claudiamatos', 'Empregado'),
(gen_random_uuid (), 'Denize Talar','denizetalar', 'denizetalar', 'Empregado'),
(gen_random_uuid (), 'Flavia Julia','flaviajulia', 'flaviajulia', 'Empregado'),
(gen_random_uuid (), 'Diana Maer','dianamaer', 'dianamaer', 'Empregado'),
(gen_random_uuid (), 'Gabriela Host','gabrielahost', 'gabrielahost', 'Empregado'),
(gen_random_uuid (), 'Jasmim Rosa','jasmimrosa', 'jasmimrosa', 'Empregado'),
(gen_random_uuid (), 'Helena Fortes','helenafortes', 'helenafortes', 'Empregado'),
(gen_random_uuid (), 'Barbara Lopes','barbaralopes', 'barbaralopes', 'Empregado'),
(gen_random_uuid (), 'Lilian Ralo','lilianralo', 'lilianralo', 'Empregado'),
(gen_random_uuid (), 'Laura Silva','laurasilva', 'laurasilva', 'Empregado'),
(gen_random_uuid (), 'Cassia Patos','cassiapatos', 'cassiapatos', 'Empregado'),
(gen_random_uuid (), 'Marisa Luz','marialuz', 'marialuz', 'Empregado'),
(gen_random_uuid (), 'Iris de Oliveira','irisoliveira', 'irisoliveira', 'Empregado'),
(gen_random_uuid (), 'Paloma Reis','palonareis', 'palonareis', 'Empregado'),
(gen_random_uuid (), 'Bia Marques','biamarques', 'biamarques', 'Gerente'),
(gen_random_uuid (), 'Eduarda Vale','eduardavale', 'eduardavale', 'Empregado'),
(gen_random_uuid (), 'Jaqueline Yat','jaquelineyat', 'jaquelineyat', 'Empregado'),
(gen_random_uuid (), 'Raquel Datas','raqueldatas', 'raqueldatas', 'Empregado'),
(gen_random_uuid (), 'Bruna Gil','brunagil', 'brunagil', 'Gerente'),
(gen_random_uuid (), 'Carolina Martins','carolinamartins', 'carolinamartins', 'Empregado'),
(gen_random_uuid (), 'Silvana Silva','silvanasilva', 'silvanasilva', 'Empregado'),
(gen_random_uuid (), 'Valentina Santos','valentinasantos', 'valentinasantos', 'Empregado'),
(gen_random_uuid (), 'Valeria Castro','valeriacastro', 'valeriacastro', 'Empregado'),
(gen_random_uuid (), 'Virginia Celta','virginiacelta', 'virginiacelta', 'Empregado'),
(gen_random_uuid (), 'Yara Atlas','yaraaltlas', 'yaraaltlas', 'Empregado'),
(gen_random_uuid (), 'Tais Joma','taisjoma', 'taisjoma', 'Empregado'),
(gen_random_uuid (), 'Carla Mara','carlamara', 'carlamara', 'Empregado'),
(gen_random_uuid (), 'Bella Dela','belladela', 'belladela', 'Empregado'),
(gen_random_uuid (), 'Gloria Maria','gloriamaria', 'gloriamaria', 'Empregado'),
(gen_random_uuid (), 'Maria Flavia','mariaflavia', 'mariaflavia', 'Empregado'),
(gen_random_uuid (), 'Nima Flores','nimaflores', 'nimaflores', 'Empregado'),
(gen_random_uuid (), 'Ana Flavia','anaflavia', 'anaflavia', 'Empregado'),
(gen_random_uuid (), 'Antonia Gular','antoniagular', 'antoniagular', 'Empregado'),
(gen_random_uuid (), 'Antonio Gular','antoniogular', 'antoniogular', 'Gerente'),
(gen_random_uuid (), 'Antonio Jose','antoniojose', 'antoniojose', 'Empregado'),
(gen_random_uuid (), 'Antonio Justo','antoniojusto', 'antoniojusto', 'Empregado'),
(gen_random_uuid (), 'Ana Luz','analuz', 'analuz', 'Empregado'),
(gen_random_uuid (), 'Luisa Ka','luisaka', 'luisaka', 'Empregado'),
(gen_random_uuid (), 'Karla Tar','karlatar', 'karlatar', 'Empregado'),
(gen_random_uuid (), 'Selma Dout','selmadout', 'selmadout', 'Empregado'),
(gen_random_uuid (), 'Salete Bela','saletebela', 'saletebela', 'Empregado'),
(gen_random_uuid (), 'Isadora Hot','isadorahot', 'isadorahot', 'Empregado'),
(gen_random_uuid (), 'Izabel Yae','izabelyae', 'izabelyae', 'Empregado'),
(gen_random_uuid (), 'Patrica Gama','patriciagama', 'patriciagama', 'Empregado'),
(gen_random_uuid (), 'Douglas Santos','dolglassantos', 'dolglassantos', 'Gerente'),
(gen_random_uuid (), 'Daniel Gama','danielgama', 'danielgama', 'Empregado'),
(gen_random_uuid (), 'Danilo Gama','danilogama', 'danilogama', 'Empregado'),
(gen_random_uuid (), 'Gustavo Gama','gustavogama', 'gustavogama', 'Empregado'),
(gen_random_uuid (), 'Gustavo Nogueira','gustavonogueira', 'gustavonogueira', 'Empregado'),
(gen_random_uuid (), 'Antonio Heizer','antonioheizer', 'antonioheizer', 'Empregado'),
(gen_random_uuid (), 'Antonio Yua','antonioyua', 'antonioyua', 'Empregado'),
(gen_random_uuid (), 'Henrique Badaro','hemriquebadaro', 'hemriquebadaro', 'Empregado'),
(gen_random_uuid (), 'Paulo Pontes','paulopontes', 'paulopontes', 'Empregado'),
(gen_random_uuid (), 'Paulo Jose','paulojose', 'paulojose', 'Empregado'),
(gen_random_uuid (), 'Guilherme Quat','guilhermequat', 'mariacosta', 'Gerente'),
(gen_random_uuid (), 'Mateus Nato','mateusnato', 'mateusnato', 'Empregado'),
(gen_random_uuid (), 'Murilo Bento','murilobento', 'murilobento', 'Empregado'),
(gen_random_uuid (), 'Mauricio Menezes','mauriciomenezes', 'mauriciomenezes', 'Empregado'),
(gen_random_uuid (), 'Felipe Costa','felipecosta', 'felipecosta', 'Empregado'),
(gen_random_uuid (), 'Pedro Antunes','pedroantunes', 'pedroantunes', 'Empregado'),
(gen_random_uuid (), 'Vitor Pad','vitorpad', 'vitorpad', 'Empregado'),
(gen_random_uuid (), 'Davi Luis','daviluis', 'daviluis', 'Empregado'),
(gen_random_uuid (), 'Ezequiel Gama','ezequielgama', 'ezequielgama', 'Empregado'),
(gen_random_uuid (), 'Izaquias Flores','izaquiasflores', 'izaquiasflores', 'Empregado'),
(gen_random_uuid (), 'Marlon Brando','marlobrando', 'marlobrando', 'Empregado'),
(gen_random_uuid (), 'Marlon Baleia','marlonbaleia', 'marlonbaleia', 'Empregado'),
(gen_random_uuid (), 'Nicolas Trata','nicolastrata', 'nicolastrata', 'Empregado'),
(gen_random_uuid (), 'Geraldo Trata','geraldotrata', 'geraldotrata', 'Empregado'),
(gen_random_uuid (), 'Guilherme Aparecido','guilhermeaparecido', 'guilhermeaparecido', 'Gerente'),
(gen_random_uuid (), 'Joao Carlos','joaocarlos', 'joaocarlos', 'Empregado'),
(gen_random_uuid (), 'Carlos Joao','carlosjoao', 'carlosjoao', 'Empregado'),
(gen_random_uuid (), 'Claudio Carias','claudiocarias', 'claudiocarias', 'Empregado'),
(gen_random_uuid (), 'Carlos Truma','carlostruma', 'carlostruma', 'Empregado'),
(gen_random_uuid (), 'Igor Fala','igorfala', 'igorfala', 'Empregado'),
(gen_random_uuid (), 'Igor Faria','igorfaria', 'igorfaria', 'Empregado'),
(gen_random_uuid (), 'Lucio Gal','luciogal', 'luciogal', 'Empregado'),
(gen_random_uuid (), 'Wesley Cabral','wesleycabral', 'wesleycabral', 'Empregado'),
(gen_random_uuid (), 'Wilson Luiz','wilsonluiz', 'wilsonluiz', 'Empregado'),
(gen_random_uuid (), 'Yago Joa','yagojoa', 'yagojoa', 'Empregado'),
(gen_random_uuid (), 'Tomas Aquino','tomaaquino', 'tomaaquino', 'Empregado'),
(gen_random_uuid (), 'Pablo Neruda','pabloneruda', 'mariacosta', 'Empregado'),
(gen_random_uuid (), 'Guilherme Heizer Nogueira','guilhermeheizer', 'guilhermeheizer', 'Gerente'),
(gen_random_uuid (), 'Luan Gat','luangat', 'luangat', 'Empregado'),
(gen_random_uuid (), 'Patrick Hel','patrickhel', 'patrickhel', 'Empregado'),
(gen_random_uuid (), 'Renato Roa','renatoroa', 'renatoroa', 'Empregado'),
(gen_random_uuid (), 'Renato Vista','renatovista', 'renatovista', 'Empregado'),
(gen_random_uuid (), 'Renata Vista','renatavista', 'renatavista', 'Empregado'),
(gen_random_uuid (), 'Heitor Bara','heitorbara', 'heitorbara', 'Empregado'),
(gen_random_uuid (), 'Hector Heitor','hectorheitor', 'hectorheitor', 'Empregado'),
(gen_random_uuid (), 'Jaime Gama','jaimegama', 'jaimegama', 'Empregado'),
(gen_random_uuid (), 'Isac Gama','isacgama', 'isacgama', 'Empregado'),
(gen_random_uuid (), 'Lucca Dalta','luccadalta', 'luccadalta', 'Empregado'),
(gen_random_uuid (), 'Renan Ribeiro','renanribeiro', 'renanribeiro', 'Empregado'),
(gen_random_uuid (), 'Roberto Boa','robertoboa', 'robertoboa', 'Empregado'),
(gen_random_uuid (), 'Elias Wall','eliaswall', 'eliaswall', 'Empregado'),
(gen_random_uuid (), 'Marcio Augusto','marcioaugusto', 'marcioaugusto', 'Empregado'),
(gen_random_uuid (), 'Sergio For','sergiofor', 'sergiofor', 'Empregado'),
(gen_random_uuid (), 'Gabel Ual','gabelual', 'gabelual', 'Empregado');

select * from public."Usuario";

INSERT INTO public."Tarefa"("TarCodigo", "TarNome", "TarDataInicio", "TarDataFinal", "TarStatus") VALUES 
(11, 'Number One Inglês Aula', '2019-03-01 09:21:11', null, 2),
(12, 'Number One Inglês Estudo', '2019-03-01 09:21:11', null, 2),
(13, 'Márcio Aula Particular Inglês Estudo', '2019-03-01 09:21:11', null, 2),
(14, 'Márcio Aula Particular Inglês Estudo', '2019-03-01 09:21:11', null, 2),
(16, 'Inglês Filme', '2019-03-01 09:21:11', null, 2),
(17, 'Inglês Vídeo', '2019-03-01 09:21:11', null, 2),
(21, 'JAvascript', '2023-10-21 12:21:11', null, 2),
(31, 'Mobile Video Aula', '2019-03-01 09:21:11', null, 2),
(32, 'Mobile Estudo', '2019-03-01 09:21:11', null, 2),
(41, 'Ionic 5 Aula', '2019-11-14 13:51:11', null, 2),
(42, 'Ionic 5 Estudo', '2019-03-01 09:21:11', null, 2),
(51, 'C# Curso Completo: Do Básico ao Avançado Video Aula', '2021-07-23 08:21:11', null, 2),
(52, 'C# Curso Completo: Do Básico ao Avançado Estudo', '2019-03-01 09:21:11', null, 2),
(53, 'C# Estudo', '2019-03-01 09:21:11', null, 2),
(54, 'Curso de ASP .NET Core MVC - Criando um Site do Zero (NET 6) Video aula', '2019-03-01 09:21:11', null, 2),
(55, 'Curso de ASP .NET Core MVC - Criando um Site do Zero (NET 6) Estudo', '2019-03-01 09:21:11', null, 2),
(57, 'Curso de Desenvolvimento de APIs com C# Estudo', '2019-03-01 09:21:11', null, 2),
(56, 'Curso Microsoft Csharp Estudo', '2019-03-01 09:21:11', null, 2),
(61, 'Cobol IBM', '2019-03-01 09:21:11', null, 2),
(71, 'Curso Python Aula', '2019-03-01 09:21:11', null, 2),
(72, 'Curso Python Estudo', '2019-03-01 09:21:11', null, 2),
(73, 'Curso Python Exercicio', '2019-03-01 09:21:11', null, 2),
(74, 'NTT DATA - Engenharia de Dados com Python Aula', '2019-03-01 09:21:11', null, 2),
(75, 'NTT DATA - Engenharia de Dados com Python Estudo', '2019-03-01 09:21:11', null, 2),
(76, 'NTT DATA - Engenharia de Dados com Python Exercicio', '2019-03-01 09:21:11', null, 2),
(77, 'Suzano - Análise de Dados com Power BI Aula', '2019-03-01 09:21:11', null, 2),
(78, 'Suzano - Análise de Dados com Power BI Estudo', '2019-03-01 09:21:11', null, 2),
(79, 'Suzano - Análise de Dados com Power BI Exercicio', '2019-03-01 09:21:11', null, 2),
(81, 'Curso SQL Aula', '2019-03-01 09:21:11', null, 2),
(91, 'Curso de JavaScript Aula', '2019-03-01 09:21:11', null, 2),
(101, 'Carol Martins Aula', '2019-03-01 09:21:11', null, 2),
(102, 'Carol Martins Exercicio', '2019-03-01 09:21:11', null, 2);

UPDATE public."Tarefa"
SET "TarDataFinal"= "TarDataInicio"
where "TarStatus" <> 3;

